#!/bin/bash

# Ensuring ZSH is our shell
chsh -s /bin/zsh

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

pushd "$DOTFILES" || exit
for folder in ${STOW_FOLDERS//,/ }
do
    stow "$folder" --dotfiles --target "$HOME"
done
popd || exit

source $HOME/.zshrc

packages="$(cat ./packages.txt | ./parse_packages_file $OS)"

read -e -p "Do you want to create a new SSH key? [y/N]> " choice
[[ "$choice" == [Yy]* ]] && ssh-keygen

echo "Packages: $packages"
read -e -p "Do you want to install those packages? [y/N]> " choice
[[ "$choice" == [Yy]* ]] && sudo dnf install $packages --skip-unavailable

git clone https://github.com/tmux-plugins/tpm "$TPM_INSTALL"

git config --global user.name "${GIT_USERNAME}"
git config --global user.email "${GIT_EMAIL}"
git config --global init.defaultBranch "${GIT_DEFAULT_BRANCH}"
