#!/usr/bin/env sh

# bar settings
yabai -m config top_padding 0

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autofocus

yabai -m config window_placement             second_child
yabai -m config window_topmost               off

yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on

yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

# Mouse support
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# space settings
yabai -m config layout                       bsp
yabai -m config --space 1 layout             float
yabai -m config --space 3 layout             stack
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0

#yabai -m rule --add app='.*' space=^1
yabai -m rule --add app='^(kitty)$' space=2
yabai -m rule --add app='^(Safari|Firefox Developer Edition|Brave Browser|qutebrowser)$' space=3
yabai -m rule --add app='^(Microsoft Outlook|Microsoft Teams|Discord|Slack)$' space=4
yabai -m rule --add app='^Obsidian$' space=5

# float rules
yabai -m rule --add space=1 manage=off

yabai -m rule --add app='^(Calculator|Software Update|Dictionary|System Preferences|System Settings|Activity Monitor)$' manage=off
yabai -m rule --add label='Finder' app='^Finder$' manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add app='^LuLu$' manage=off
yabai -m rule --add app='^Messages$' manage=off
yabai -m rule --add title='^JetBrains Toolbox$' manage=off
yabai -m rule --add app='^1Password$' manage=off
yabai -m rule --add app='^Geforce Now$' manage=off
yabai -m rule --add app='^FaceTime$' manage=off
yabai -m rule --add app='^(Firefox Developer Edition|Google Chrome)$' title='^Dev(eloper )?Tools' manage=off
yabai -m rule --add app='^Docker Desktop$' manage=off

# spacebar padding on top screen
SPACEBAR_HEIGHT=$(spacebar -m config height)
yabai -m config external_bar all:$SPACEBAR_HEIGHT:0

echo "yabai configuration loaded.."

