#!/usr/bin/env bash
# shellcheck disable=SC2139

alias composer='docker run --rm -it -v "$PWD":/app -v ${COMPOSER_HOME:-$HOME/.composer}:/tmp composer '
alias composer1='docker run --rm -it -v "$PWD":/app -v ${COMPOSER_HOME:-$HOME/.composer}:/tmp composer:1 '
alias node='docker run --rm -it -v "$PWD":/app -w /app node:16-alpine '
alias node20='docker run --rm -it -v "$PWD":/app -w /app node:20-alpine '
alias node16='docker run --rm -it -v "$PWD":/app -w /app node:16-alpine '
alias node14='docker run --rm -it -v "$PWD":/app -w /app node:14-alpine '
alias npm='docker run --rm -it -v "$PWD":/app -w /app node:16-alpine npm '
alias deno='docker run --rm -it -v "$PWD":/app -w /app denoland/deno '
alias aws='docker run --rm -it -v ~/.aws:/root/.aws amazon/aws-cli '
alias ffmpeg='docker run --rm -it -v "$PWD":/app -w /app jrottenberg/ffmpeg '
alias yo='docker run --rm -it -v "$PWD":/app nystudio107/node-yeoman:16-alpine '
alias dk='docker'
alias dc='docker-compose'
alias dkill='docker stop $(docker ps -q)'
alias dlast='docker exec -it $(docker ps -l -q)'

alias timew='$HOME/.local/scripts/timew_hooks_proxy.sh /opt/homebrew/bin/timew'
alias tw='timew'
alias opena="open -a"

alias vi="$VIM"
alias vim="$VIM"
alias vims="NVIM_LISTEN_ADDRESS=/tmp/nvim $VIM"
alias work="cd ~/work"

alias python="python3"
alias cbp="cat $DOTFILES/zsh/.config/.zsh_profile"
alias ebp="$VIM $DOTFILES/.zsh_profile"
alias etc="$VIM $DOTFILES/awesome-streamerrc/ThePrimeagen/.tmux.conf"
alias bp="dotFileInstall && source ~/.zshrc"
alias yolo="git push origin master --force --no-verify"
alias eirc="nvim $XDG_CONFIG_HOME/i3/i3config"
alias cvrc="cat $DOTFILES/vimrc/.vimrc"
alias dotFileInstall="$DOTFILES/install"

alias gitinitdir='git init && git commit -m "batman" --allow-empty && gh repo create ${PWD##*/} --push -s . '
alias goinitdir='go mod init "github.com/dGilli/${PWD##*/}"'
